apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vzze399ji-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vzze399ji-go 
  name: vzze399ji-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: vzze399ji-go 
